version: '3'
services:
  mongo:
    container_name: mongo
    image: mongo:4.0.3
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"
    
  api:
    container_name: clean-api
    image: node:16.17.0
    working_dir: /usr/src/clean-api
    restart: always
    command: bash -c "yarn install --production --frozen-lockfile && yarn start"
    volumes:
      - ./dist/:/usr/src/clean-api/dist/
      - ./package.json:/usr/src/clean-api/package.json
      - ./yarn.lock:/usr/src/clean-api/yarn.lock
    links:
      - mongo
    ports:
      - "5050:5050"